
version: "3"

services:
  # presentation
  #   Server for hosting the main keynote provider.
  #   '/index.html' references the slides of the '/Presentation/Slides' volume.
  presentation:
    build: .
    container_name: presentation
    ports:
      - 8000:8000
    volumes:
      - "./Slides:/Presentation/Slides:rw"
      - "./Shared/Generated-Index.html:/Presentation/index.html:ro"

  # autoindex
  #   Populates the 'output.html' volume at boot, and when the '/watch' volume
  #   sent create or delete events from the filesystem. It generates an output
  #   based on 'input.html'.
  autoindex:
    build: ./I-Notify
    container_name: autoindex
    volumes:
      - "./Slides:/watch:ro"
      - "./I-Notify:/tools:ro"
      - "./Shared/Template.html:/input.html:ro"
      - "./Shared/Generated-Index.html:/output.html:rw"
    entrypoint: /tools/Make.sh
